### ISSUE TITLE
Windows11

### ISSUE THREAD

**Issue by Cherryman99** [janaboy74/wfeditormk66#1]
Newbie here, how di i (compile?) get it working for windows 11

Like to try it!

**Comment by janaboy74** [comment]
The win64 binaries should work out of the box.

**Comment by Cherryman99** [comment]
I get multiple errors about not finding the .dll files when i try to run it.

**Comment by janaboy74** [comment]
You have two options:
- You can run the sfx package directly. It should work without the dll problems.
- The better way is to unpack the 7z content into a Folder with all the dll-s.
The exe will search the dll-s from the same folder where you run it.

**Comment by Cherryman99** [comment]
Sorry, tried both options.
Both give me the .dll not found message.

**Comment by janaboy74** [comment]
What is the name of the dll?

**Comment by Cherryman99** [comment]
a few of them, After clicking the exe:
1. libgio-2.0-0.dll
2. libglib -2.0-0.dll
3. libgcc_s_seh-1.bll
4. libstdcc++-6.dll

It  looks like the filenames the exe calls are the old ones ?

**Comment by janaboy74** [comment]
The problem was, that I have tested on my machine where Gimp was installed and the software found the necessary components from it.
Now I have tested on a fresh installed Windows(VM) an it works.
Can you try it now with the updated packages?

**Comment by Cherryman99** [comment]
> The problem was, that I have tested on my machine where Gimp was installed and the software found the necessary components from it. Now I have tested on a fresh installed Windows(VM) an it works. Can you try it now with the updated packages?<


I tried the 7z , and it now it opens the program and GUI.
Edit: .exe idem. 

But wen i try load, it crashes.

**Comment by janaboy74** [comment]
Hi!

The version v0.5.2. should fix the problem.
It is still recommended to save the work frequently while using periodically different names, because the software can still contain errors.
