### ISSUE TITLE
Loads but black screen in the building area

### ISSUE THREAD

**Issue by ryankruger08** [janaboy74/wfeditormk66#2]
Hi i am on windows 11 and when i try to load the editor it is a fully black screen in the editor but the toolbars are all still there and when i try to put a thing on there to begin making the watchface it crashes

**Comment by Chickenking9080** [comment]
![Uploading image_2023-12-30_084446961.png…]()

**Comment by janaboy74** [comment]
Could you please give me a step-by-step reproduction and a screenshot would be also nice. Or you can record a video of the window until the crash. Maybe with this: https://apps.microsoft.com/detail/9N27GQ6MLS5S ( untested ).
I will probably add a crash handler to the product if I will have time for it.

**Comment by janaboy74** [comment]
I made a new version with a lot of bugfixes. Maybe it helps. It is still not as stable as the linux version, but I hope it solves your issue.

**Comment by ryankruger08** [comment]
Thankyou! it is now working but is it possible also to edit the images and put a different one on there?
: edit I got it working

**Comment by janaboy74** [comment]
Good to hear! 😃
